# Generated by Django 5.1.4 on 2024-12-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('employee_code', models.CharField(max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
