# Generated by Django 5.1.4 on 2024-12-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_break_end_time_overtimerequest_break_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimerequest',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='overtimerequest',
            name='project_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
